- src/main/java/org/mule/module/apikit/Configuration.java
- src/main/java/org/mule/module/apikit/validation/body/schema/v1/RestXmlSchemaValidator.java
- src/test/munit/xml-doctype/xml-doctype-server.xml
- src/test/munit/xml-doctype/xml-doctype-test-suite.xml
- src/test/resources/munit/xml-doctype/resources/Note.dtd
- src/test/resources/munit/xml-doctype/resources/Note.xsd
- src/test/resources/munit/xml-doctype/resources/test.xml
- src/test/resources/munit/xml-doctype/xml-doctype.raml
> APIKIT-1997: DOCTYPE is not allowed despite enabling expandExternalEntities

- src/main/java/org/mule/module/apikit/validation/attributes/QueryParameterValidator.java
- src/test/munit/parameters/query-parameters/query-params-test-suite.xml
> APIKIT-2019: APIKIT does not Handle Exceptions Properly on Query Parameter Validation

- src/main/java/org/mule/module/apikit/helpers/AttributesHelper.java
- src/main/java/org/mule/module/apikit/validation/attributes/QueryParameterValidator.java
- src/test/munit/parameters/query-parameters/query-params-test-suite.xml
- src/test/resources/munit/parameters/query-parameters.raml
> APIKIT-2058: query params with default values and without query params in request are broken

- pom.xml
Reverts mulesoft/apikit-rest-module#182
> Revert "Update dependency org.mule.services:mule-service-scheduler to v1.3.2"

- pom.xml
Reverts mulesoft/apikit-rest-module#132
> Revert "Update jackson.version to v2.11.1"

- pom.xml
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
> Update dependency junit:junit to v4.13.1 [SECURITY] (#314)

- pom.xml
- src/test/java/org/mule/module/apikit/validation/QueryParamsRequestValidatorTestCase.java
- src/test/resources/unit/query-parameters/query-parameters.raml
This reverts commit a112a2fe6dbf4bce7961e081ccad45e921bf54bb.
> Revert "Revert "APIKIT-2843: APIKit v.1.3.14 and above no longer accepts query parameters of type any  (#369)" (#393)"

- pom.xml
Reverts mulesoft/apikit-rest-module#404
> Revert "Update version to release 1.5.0"

- src/test/java/org/mule/module/apikit/RamlHandlerTestCase.java
This reverts commit a3adebd8372fdc191834a79cb870a7816c487fff.
> W-12698849: Revert "W-11659429: Adopt AMF 5 (#628)"

- src/test/java/org/mule/module/apikit/RamlHandlerTestCase.java
This reverts commit a3adebd8372fdc191834a79cb870a7816c487fff.
> Revert "W-11659429: Adopt AMF 5 (#628)" (#659)

- src/main/java/org/mule/module/apikit/validation/body/form/transformation/MultipartBuilder.java
- src/test/java/org/mule/module/apikit/validation/body/form/MultipartFormValidatorTest.java
Made patterns fully case-insensitive.
> W-12964758: multipart headers are case-insensitive

- src/main/java/org/mule/module/apikit/validation/attributes/HeadersValidator.java
> W-15162242: MimeType compatibility requires both type and subtype to be compatible (#758)

- pom.xml
* Disable mycilla plugin
* Update scope of plugins
> @W-16552229 - Update scope of plugins (#794)

- pom.xml
Updating transitive dependencies
> W-16828930: Update transitive dependencies

- pom.xml
> W-17227894 : setting commons-collections4 dependency in pom and update parser service version

- pom.xml
Updated apiconsole dependency uses DOMPurify v2.5.7
> W-17450859: Update apiconsole dependency

- .gitignore
- build.yaml
- pom.xml
* MUnit dependency update
* Update runtime latest version
> W-17348862: MUnit dependency update (#832)

- src/main/java/org/mule/module/apikit/api/deserializing/ArrayHeaderDelimiter.java
- src/main/java/org/mule/module/apikit/deserializing/MimeType.java
- src/test/java/org/mule/module/apikit/deserializing/MimeTypeTest.java
Cherry pick : https://github.com/mulesoft/apikit-rest-module/pull/841
> W-17760021 cherry

- pom.xml
cherry: https://github.com/mulesoft/apikit-rest-module/pull/842
> W-17902163 cherryx

- .gitignore
- build.yaml
- pom.xml
> W-17905722: cherry pick commits from main
